// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1kdxcxA8YuJBjEizIC43RSpkE3SFfnug',
    appId: '1:52998576128:web:c4821a181d876ce2bfe0e5',
    messagingSenderId: '52998576128',
    projectId: 'chatsync-c737a',
    authDomain: 'chatsync-c737a.firebaseapp.com',
    storageBucket: 'chatsync-c737a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4FYOcmgIJsW6n2Lo8_0c_TVnormMUyNk',
    appId: '1:52998576128:android:b8c881bcd1ac7220bfe0e5',
    messagingSenderId: '52998576128',
    projectId: 'chatsync-c737a',
    storageBucket: 'chatsync-c737a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvWrJEFHsP6p88fPRtX7HvNlkZHdJdx0c',
    appId: '1:52998576128:ios:ee01ab445276aa9ebfe0e5',
    messagingSenderId: '52998576128',
    projectId: 'chatsync-c737a',
    storageBucket: 'chatsync-c737a.appspot.com',
    androidClientId: '52998576128-7oq8tjp0ikd77smikguomp8pjlb9ke41.apps.googleusercontent.com',
    iosClientId: '52998576128-v4earmj5n8a87ke029e9nrjmq98lso9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvWrJEFHsP6p88fPRtX7HvNlkZHdJdx0c',
    appId: '1:52998576128:ios:dd428a6edc030a02bfe0e5',
    messagingSenderId: '52998576128',
    projectId: 'chatsync-c737a',
    storageBucket: 'chatsync-c737a.appspot.com',
    androidClientId: '52998576128-7oq8tjp0ikd77smikguomp8pjlb9ke41.apps.googleusercontent.com',
    iosClientId: '52998576128-6fqjvaljepo3s8e6g3kqtv3ru6d01543.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatSync.RunnerTests',
  );
}
